---
title: "Week 06 - Prediction"
subtitle: "In Class Exercise: Access to Information and Attitudes towards Intimate Partner Violence<html><div style='float:left'></div><hr color='#EB811B' size=1px width=800px></html>"
author: "Danilo Freire"
date: "27th February 2019"
output: 
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    nature: 
      beforeInit: "macros.js"
      highlightStyle: github
      ratio: 4:3
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
r <- getOption("repos")
r["CRAN"] <- "http://cran.cnr.berkeley.edu/"
options(repos = r)
set.seed(12345)
```

<style>

.remark-slide-number {
  position: inherit;
}

.remark-slide-number .progress-bar-container {
  position: absolute;
  bottom: 0;
  height: 6px;
  display: block;
  left: 0;
  right: 0;
}

.remark-slide-number .progress-bar {
  height: 100%;
  background-color: #EB811B;
}

.orange {
  color: #EB811B;
}
</style>

# Partner Violence 

.font130[
In this exercise, we examine cross-national differences in attitudes towards domestic violence and access to information. We explore the hypothesis that there is an association at an aggregate level between the extent to which individuals in a country have access to knowledge and new information, both through formal schooling and through the mass media, and their likelihood of condemning acts of intimate partner violence.  This exercise is in part based on: 

Pierotti, Rachel. (2013). "[Increasing Rejection of Intimate Partner Violence: Evidence of Global Cultural Diffusion](http://dx.doi.org/10.1177/0003122413480363)." *American Sociological Review*, 78: 240-265. 
]
---

# Partner Violence 

.font130[
We use data from the Demographic and Health Surveys, which are a set of over 300 nationally, regionally and residentially representative surveys that have been fielded in developing countries around the world, beginning in 1992. The surveys have identical questionnaires and trainings for interviewers, enabling the data from one country to be directly compared with data collected in other countries. It is important to note that different groups of countries are surveyed every year.
]
---

# Partner Violence 

.font150[
In the study, the author used these data to show that "women with greater access to global cultural scripts through urban living, secondary education, or access to media were more likely to reject intimate partner violence." The data set is in the csv file [dhs_ipv.csv](https://raw.githubusercontent.com/pols1600/pols1600.github.io/master/datasets/measurement/dhs_ipv.csv). The names and descriptions of variables are:
]
---

# Partner Violence 

|Name            | Description
|:---------------|:-----------------------|
|`beat_goesout`  |Percentage of women in each country that think a husband is justified to beat his wife if she goes out without telling him.| 
|`beat_burnfood` | Percentage of women in each country that think a husband is justified to beat his wife if she burns his food. | 
|`no_media`      | Percentage of women in each country that rarely encounter a newspaper, radio, or television.| 
|`sec_school`    | Percentage of women in each country with secondary or higher education.|
|`year`          | Year of the survey|
|`region`        | Region of the world|
|`country`       | Country|
---
# Partner Violence 

.font150[
Note that there are two indicators of *attitudes towards domestic violence*: `beat_goesout` and `beat_burnfood`. There are also two indicators of *access to information*: `sec_school` and `no_media`. 
]
---

# Question 1

.font130[
Let's begin by examining the association between attitudes towards intimate partner violence and the two exposure to information variables in our data. Load the `dhs_ipv.csv` data set. Use scatterplots to examine the bivariate relationship between `beat_goesout` and `no_media` as well as between `beat_goesout` and `sec_school`. Repeat these bivariate graphs between `beat_burnfood` and  `no_media`, as well as `beat_burnfood` and `sec_school`. Be sure to add informative axis labels. Briefly interpret these graphs in light of the hypothesis of the study.
]
---

# Question 2

.font130[
Compute the correlation coefficient between `beat_burnfood` and media exposure, as well as between `beat_burnfood` and education. Remember to use complete observations. What do these measures tell us about the association between education and media exposure with attitudes towards intimate partner violence?
]
---

# Question 3

.font130[
We proceed to explore the national-level differences in attitudes towards domestic violence. First, use boxplots to compare the variation in the percentage of `beat_burnfood` between different regions of the world using `region`. What are the main differences across regions in terms of the median and dispersion of the distribution?  Second, using boxplots examine the distribution of `no_media` and `sec_school` by region of the world. Comment on the main differences of the distribution of these variables across regions. 
]
---

# Extra Question:

.font130[
An important point of the researcher's hypothesis is that the support towards intimate partner violence should *decrease* over time, as more women across regions have access to formal schooling and exposure to mass media. To test this idea, using time-series plots, examine the trends in `beat_burnfood` from 1999-2014 *within each region*. Thinking about the study design, what should we consider before trusting that this plot shows a change over time in attitudes? 
]

---
class: inverse, center, middle

# See You on Friday!  

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=720px></html> 
