---
title: "Week 02 - Introduction to Causality"
subtitle: "Success of Leader Assassination as a Natural Experiment <html><div style='float:left'></div><hr color='#EB811B' size=1px width=800px></html>"
author: "Danilo Freire"
date: "1st February 2019"
output: 
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    nature: 
      beforeInit: "macros.js"
      highlightStyle: github
      ratio: 4:3
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
r <- getOption("repos")
r["CRAN"] <- "http://cran.cnr.berkeley.edu/"
options(repos = r)
```

<style>

.remark-slide-number {
  position: inherit;
}

.remark-slide-number .progress-bar-container {
  position: absolute;
  bottom: 0;
  height: 6px;
  display: block;
  left: 0;
  right: 0;
}

.remark-slide-number .progress-bar {
  height: 100%;
  background-color: #EB811B;
}

.orange {
  color: #EB811B;
}
</style>


# Class Exercise on Causality

.font150[
* Partial replication of: Jones, Benjamin F, and Benjamin A Olken. 2009. [Hit or Miss? The Effect of Assassinations on Institutions and War.](http://dx.doi.org/10.1257/mac.1.2.55) *American Economic Journal: Macroeconomics* 1(2): 55–87. 
]

.font110[
* **Abstract**: Assassinations are a persistent feature of the political landscape. Using a new dataset of assassination attempts on all world leaders from 1875 to 2004, we exploit inherent randomness in the success or failure of assassination attempts to identify the effects of assassination. We find that, on average, successful assassinations of autocrats produce sustained moves toward democracy. We also find that assassinations affect the intensity of small-scale conflicts. The results document a contemporary source of institutional change, inform theories of conflict, and show that small sources of randomness can have a pronounced effect on history.
]
---

# Class Exercise on Causality

.font130[One longstanding debate in the study of international relations concerns the question of whether individual political leaders can make a difference.  Some emphasise that leaders with different ideologies
and personalities can significantly affect the course of a nation. Others argue that political leaders are severely constrained by historical and institutional forces.  Did individuals like Hitler, Mao, Roosevelt, and Churchill make a big difference?  The difficulty of empirically testing these arguments stems from the fact that the change of leadership is not random and there are many confounding factors to be adjusted for.]
---

# Class Exercise on Causality

.font150[
* In this exercise, we consider a *natural experiment* in which the success or failure of assassination attempts is assumed to be essentially random.

* Each observation of the CSV data set `leaders.csv` contains information about an assassination attempt. 

* The variables are:
]
---

# Class Exercise on Causality

.font120[
--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `country`            The name of the country
 
 `year`               Year of assassination
 
 `leadername`         Name of leader who was targeted
 
 `age`                Age of the targeted leader
 
 `politybefore`       Average polity score during the 3 year period prior to the attempt
 
 `polityafter`        Average polity score during the 3 year period after the attempt
]

---

# Class Exercise on Causality

.font120[
--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `civilwarbefore`     1 if country is in civil war during the 3 year period prior to the attempt, or 0 
 
 `civilwarafter`      1 if country is in civil war during the 3 year period after the attempt, or 0
 
 `interwarbefore`     1 if country is in international war during the 3 year period prior to the attempt, or 0
 
 `interwarafter`      1 if country is in international war during the 3 year period after the attempt, or 0
 
 `result`             Result of the assassination attempt

]
---

# Class Exercise on Causality

.font130[
The `polity` variable represents the so-called *polity score* from the Polity Project.  The Polity Project systematically documents and quantifies the regime types of all countries in the world from 1800.  The polity score is a 21-point scale ranging from -10 (hereditary monarchy) to 10 (consolidated democracy).] 

.font130[
The `result` variable is a 10 category factor variable describing the result of each assassination attempt.]
---

# Class Exercise on Causality

.font150[
* **Question 1**

* How many assassination attempts are recorded in the data?  How many countries experience at least one leader assassination attempt? (The `unique` function, which returns a set of unique values from the input vector, may be useful here).  What is the average number of such attempts (per year) among these countries?
]
---

# Class Exercise on Causality

.font150[
* **Question 2**

* Create a new binary variable named `success` that is equal to 1 if a leader dies from the attack and to 0 if the leader survives.  Store this new variable as part of the original data frame.  What is the overall success rate of leader assassination? Does the result speak to the validity of the assumption that the success of assassination attempts is randomly determined? ]
---

# Class Exercise on Causality

.font150[
* **Question 3**

* Investigate whether the average polity score over 3 years prior to an assassination attempt differs on average between successful and failed attempts.  Also, examine whether there is any difference in the age of targeted leaders between successful and failed attempts.  Briefly interpret the results in light of the validity of the aforementioned assumption.]
---

# Class Exercise on Causality

.font150[
* **Question 4**

* Repeat the same analysis as in the previous question, but this time using the country's experience of civil and international war. Create a new binary variable in the data frame called `warbefore`.  Code the variable such that it is equal to 1 if a country is in either civil or international war during the 3 years prior to an assassination attempt.  Provide a brief interpretation of the result.]
---

# Class Exercise on Causality

.font150[
* **Question 5**

* Does successful leader assassination cause democratization? Does successful leader assassination lead countries to war?  Answer these questions by analyzing the data.  Be sure to state your assumptions and provide a brief interpretation of the results.]
---
class: inverse, center, middle

# Questions?

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=720px></html> 

---

class: inverse, center, middle

# See you next week!

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=720px></html> 